### ISSUE TITLE
Application can downtime ,When I spicify EnableRelaxedContentType: true in ResourceHandler

### ISSUE THREAD

**Issue by nwaycn** [ant0ine/go-json-rest#115]
When I must use a upload interface by go-json-rest, so I spicify EnableRelaxedContentType: true in ResourceHandler,But when the  Content-Type:[application/x-www-form-urlencoded] is found, my application is die, Tip: 

map[Accept:[*/*] Content-Length:[2] Content-Type:[application/x-www-form-url
ded] Authorization:[Basic MTAwMDoxMjM0] User-Agent:[curl/7.32.0]]
2014/12/31 10:23:29 FormFile: request Content-Type isn't multipart/form-data

how to catch this die event? and ignore it.

**Comment by ant0ine** [comment]
Re downtime: the expected behavior when a "panic" occurs in the server code is to return a 500 error.
There is an internal middleware that does that: `rest/recover.go`. Could you confirm this is the response you get ?

Re upload: You may find it easier to implement this outside of the REST api handler, on a different path. The ResourceHandler is a `net/http` handler, it does not have to serve everything, it can be combined with other handlers. Like in this example, where static files are served under `/static` while the api is under `/api`: https://github.com/ant0ine/go-json-rest#api-and-static-files
you could have `/upload` this way.
